---
title: "course25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(dplyr)
pf <- read.csv('/home/bruce/Desktop/data_analysis/r语言/r_courses/EDA_Course_Materials/EDA_Course_Materials/lesson3/pseudo_facebook.tsv',sep = '\t')
```
```{r}
ggplot(aes(x = age,y = friend_count),data = pf)+geom_point(alpha = 1/20,position = position_jitter(h =0),color = 'orange')+
  xlim(13,90)+coord_trans(y = 'sqrt')+geom_line(stat = 'summary',fun.y= mean)
cor.test(pf$age,pf$friend_count,method = 'pearson')
with(pf,cor.test(age,friend_count,method= 'pearson'))
with(subset(pf,age<70),cor.test(age,friend_count,method= 'pearson'))
```
```{r}
age_groups <- group_by(pf,age)
pf.fc_by_age <- summarise(age_groups,friend_count_mean = mean(friend_count),friend_count_median = median(friend_count),count = n())
```

```{r}
ggplot(aes(age,friend_count_mean),data = pf.fc_by_age)+ geom_line()
```
```{r}
names(pf)
```

```{r}
ggplot(aes(x = www_likes_received,y = likes_received),data = pf)+ geom_point()+
  xlim(0,quantile(pf$www_likes_received,0.95))+
  ylim(0,quantile(pf$likes_received,0.95))+
  geom_smooth(method= 'lm',color = 'red')
summary(pf$likes_received)
quantile(pf$likes_received,0.5)
with(pf,cor.test(www_likes_received,likes_received))
```
```{r}
library(alr3)
data(Mitchell)
head(Mitchell)
names(Mitchell)
ggplot(aes(x = Month , y = Temp),data = Mitchell)+ geom_point()+
  scale_x_discrete(breaks = seq(1,13))
with(Mitchell,cor.test(Month,Temp))
```
23exercise
```{r}
library(dplyr)
pf$age_with_months <-pf$age + (1 - pf$dob_month / 12)
pf.fc_by_age_months <- pf %>% 
  group_by(age_with_months) %>%
  summarise(friend_count_mean =mean(friend_count),
            friend_count_median =median(friend_count),
            n = n()) %>%
  arrange(age_with_months)
```

