---
title: "face_book"
author: "Bruce"
date: "November 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggthemes)
library(gridExtra)
pf <- read.csv('/home/bruce/Desktop/data_analysis/rÓïÑÔ/r_courses/EDA_Course_Materials/EDA_Course_Materials/lesson3/pseudo_facebook.tsv',sep = '\t')
```
```{r}
theme_set(theme_minimal(10))
# names(pf)
# qplot(x = dob_day,data = pf)+scale_x_continuous(breaks = 1:31)
gg <- ggplot(aes(x = dob_day), data = pf) + 
  geom_histogram(binwidth = 2) + 
  scale_x_continuous(breaks = 1:31) # according the month to sperate the histogram
gg+facet_grid(~dob_month)
```
```{r}
library(reshape2)
head(tips)
# View(tips)
library(ggplot2)
sp <- ggplot(tips,aes(x = total_bill,y = tip/total_bill))+geom_point(shape = 2) # shape indicate the gragh of point
sp + facet_grid(day ~ sex)
```
```{r}
ggplot(aes(x = friend_count),data = pf) + geom_histogram()
p1 <- qplot(x = friend_count,data = subset(pf,!is.na(gender)),binwidth = 25) + scale_x_continuous(limits = c(0,1000),breaks = seq(0,1000,50))+ facet_wrap(~gender,ncol = 1)
table(pf$gender)
by(pf$friend_count,pf$gender,summary)
summary(pf$friend_count)
p2 <- qplot(x = tenure/365,data = pf,binwidth = 0.25, color = I('black'),fill = I('blue'))
p3 <- qplot(x = age,data = pf,binwidth = 1,color = I('black'),fill = I('blue'))+scale_x_continuous(breaks = seq(0,113,5),limits = c(0,113))+xlab('hh')+ylab('hhh')
p3 + scale_y_sqrt()
summary(pf$age)
```

```{r}
library(gridExtra)
p1 <- ggplot(aes(x = friend_count),data = pf)+ geom_histogram()
p2 <- p1+scale_x_log10()
p3 <- p1+scale_x_sqrt()
grid.arrange(p1,p2,p3,ncol = 1)
```

```{r}
p3 <- ggplot(aes(x = friend_count),data = pf)+ geom_histogram()
p1 <-ggplot(aes(x = friend_count),data = pf)+geom_histogram()+scale_x_log10()
p2 <- ggplot(aes(x = log10(friend_count)),data = pf)+ geom_histogram()
grid.arrange(p3,p1,p2,ncol =1)
```
```{r}
qplot(x =friend_count,y = ..count../sum(..count..),data = subset(pf,!is.na(gender)),xlab= 'friend_count',ylab='proportion of users with that friend_count',binwidth=10,geom = 'freqpoly',color = gender)+
  scale_x_continuous(limits  = c(0,1000),breaks = seq(0,1000,50))
by(pf$www_likes,pf$gender,sum)
qplot(x =www_likes,data =subset(pf,!is.na(gender)),geom ='freqpoly',color = gender)+scale_x_log10()
```
```{r}
q1 <- qplot(x = gender,y = friend_count,data = subset(pf,!is.na(gender)),geom= 'boxplot')+
  scale_y_continuous(limits = c(0,250))
q2 <- qplot(x = gender,y = friend_count,data = subset(pf,!is.na(gender)),geom= 'boxplot')+
  coord_cartesian(ylim = c(0,250))
grid.arrange(q1,q2,ncol= 1)
by(pf$friend_count,pf$gender,summary)
```

```{r}
pf$mobile_check_in <- ifelse(pf$mobile_likes>0,1,0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
sum(pf$mobile_check_in ==1)/length(pf$mobile_check_in)
```

