<?php

/*
 * Implements hook_permission().
 */
function cronmonitor_permission() {
    return array(
        'administer cronmonitor' => array(
            'title' => t('Administer Cron Monitor'),
            'description' => t('Perform administration tasks for Cron Monitor.'),
        ),
    );
}


/*
 * Implements hook_menu().
 */
function cronmonitor_menu(){
    $items['admin/config/cronmonitor'] = array(
        'title' => 'Cron Monitor Settings',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cronmonitor_admin_form'),
        'access arguments' => array('administer cronmonitor'),
    );
    return $items;
}

/*
 * Administration form for Cron Monitor
 */
function cronmonitor_admin_form($form,&$form_state){
    $form['cronmonitor_enable'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Cron Monitor'),
        '#default_value' => variable_get('cronmonitor_enbale',0),
    );

    $form['cronmonitor_email_text'] = array(
        '#title' => t('Text to send with Cron Monitor Emails'),
        '#type' => 'textarea',
        '#description' => t('Enter something.'),
        '#default_value' => variable_get('cronmonitor_email_text',''),
    );

    $form['pass'] = array(
        '#type' => 'password',
        '#title' => t('Password'),
        '#maxlength' => 64,
        '#size' => 15,

    );
    return system_setting_form($form);
}