---
title: "project4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
读取文件
```{r}
wq <- read.csv('wineQualityReds.csv',sep =',')
wq <- subset(wq,select = -X)
head(wq)
```
查看变量
```{r}
dim(wq)
str(wq)
```
可知一共有1599项数据，包含了13个变量。
```{r}
summary(wq)
```
画出直方图
```{r}
library(ggplot2)
library(gridExtra)
data("diamonds")
# ggplot(aes(price),data = diamonds)+geom_histogram()
# ggplot(aes(price),data = diamonds)+geom_histogram()+scale_x_log10()
g1 <- ggplot(aes(x = quality),data = wq)+geom_histogram()

grid.arrange(g1,g1+scale_x_log10())
```
```{r}
# ggplot(aes(price),data = diamonds)+geom_histogram(binwidth = 100)
```

可知道这个质量为5,6的数量是占了大多数的了。
```{r}
str(wq)
```
```{r}
summary(wq$fixed.acidity)
ggplot(aes(fixed.acidity),data = wq)+geom_histogram()+scale_x_continuous(breaks = seq(0,16,1))
```
固定酸多数在6-9的范围
```{r}
summary(wq$volatile.acidity)
ggplot(aes(x = volatile.acidity), data = wq)+geom_histogram(binwidth = 0.05)+scale_x_continuous(breaks = seq(0,1.6,0.1))
```
柠檬酸大多数在0.3到0.65之间
```{r}
summary(wq$citric.acid)
ggplot(aes(citric.acid),data = wq)+geom_histogram()
```
```{r}
summary(wq$residual.sugar)
ggplot(aes(residual.sugar),data = wq)+geom_histogram()
```
```{r}
summary(wq$chlorides)
ggplot(aes(chlorides),data = wq)+geom_histogram()
```
```{r}
summary(wq$free.sulfur.dioxide)
ggplot(aes(free.sulfur.dioxide),data = wq)+geom_histogram()
```
```{r}
summary(wq$density)
ggplot(aes(density),data = wq)+geom_histogram()
```
```{r}
summary(wq$pH)
ggplot(aes(pH),data = wq)+geom_histogram()+scale_x_continuous(breaks = seq(0,4.0,0.1))
```
ph大多数在3-3.5之间的。并且在3.3出现了高峰。
```{r}
library(plyr)
sum(is.na(wq))
```
这里可以看出并没有缺省值。
